services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1.20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - web
    environment:
      - APP_ENV=development

  web:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    command: sleep infinity
